// SPDX-License-Identifier: Apache-2.0 OR MIT
package tags

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// goldenTargets maps a testdata/*.json fixture base name to the Target that
// produced it. Fixtures are generated by tags/testdata/gen_goldens.py from
// the reference Python "packaging" library; see that script for exact
// generation parameters.
var goldenTargets = map[string]Target{
	"windows-amd64.json": {Implementation: "cp", PyMajor: 3, PyMinor: 11, OS: "windows", Arch: "amd64"},
	"generic-py3.json":   {Implementation: "py", PyMajor: 3, PyMinor: 11, OS: "windows", Arch: "amd64"},
	"cp311_glibc228_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 11, OS: "linux", Arch: "x86_64",
		Libc: "glibc", LibcMajor: 2, LibcMinor: 28,
	},
	"cp39_glibc217_aarch64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 9, OS: "linux", Arch: "aarch64",
		Libc: "glibc", LibcMajor: 2, LibcMinor: 17,
	},
	"cp312_musl12_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 12, OS: "linux", Arch: "x86_64",
		Libc: "musl", LibcMajor: 1, LibcMinor: 2,
	},
	// A hypothetical glibc major bump. upstream assumes compatibility across
	// glibc majors, so these claim the whole glibc 2 series below them, capped
	// at the assumed last minor of an older major (lastGlibcMinor).
	"cp312_glibc35_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 12, OS: "linux", Arch: "x86_64",
		Libc: "glibc", LibcMajor: 3, LibcMinor: 5,
	},
	"cp312_glibc35_aarch64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 12, OS: "linux", Arch: "aarch64",
		Libc: "glibc", LibcMajor: 3, LibcMinor: 5,
	},
	// A hypothetical musl major bump. upstream's _musllinux.platform_tags uses
	// the major it is given verbatim, so musllinux_2_3 down to musllinux_2_0.
	"cp312_musl23_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 12, OS: "linux", Arch: "x86_64",
		Libc: "musl", LibcMajor: 2, LibcMinor: 3,
	},
	// A hypothetical Python major bump. upstream gates the stable ABI on a
	// lexicographic (major, minor) >= (3, 2), so a 4.0 target still gets abi3.
	"cp40_glibc239_x86_64.json": {
		Implementation: "cp", PyMajor: 4, PyMinor: 0, OS: "linux", Arch: "x86_64",
		Libc: "glibc", LibcMajor: 2, LibcMinor: 39,
	},
	"cp310_macos12_arm64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 10, OS: "macos", Arch: "arm64",
		MacMajor: 12, MacMinor: 0,
	},
	"cp312_macos14_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 12, OS: "macos", Arch: "x86_64",
		MacMajor: 14, MacMinor: 0,
	},
	// A declared pre-11 macOS target: the legacy major-10 minor-version walk.
	"cp39_macos1015_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 9, OS: "macos", Arch: "x86_64",
		MacMajor: 10, MacMinor: 15,
	},
	// Free-threaded (PEP 703) CPython: the cp<XY>t exact ABI, and PEP 803's
	// abi3t in place of abi3 throughout.
	"cp313t_glibc235_x86_64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 13, FreeThreaded: true,
		OS: "linux", Arch: "x86_64", Libc: "glibc", LibcMajor: 2, LibcMinor: 35,
	},
	"cp314t_macos15_arm64.json": {
		Implementation: "cp", PyMajor: 3, PyMinor: 14, FreeThreaded: true,
		OS: "macos", Arch: "arm64", MacMajor: 15, MacMinor: 0,
	},
	// PyPy: the implementation-specific "pypy<XY>_pp<IJ>" ABI, and the
	// major-only "pp3-none-any" in the compatible tier.
	"pp310_pypy73_glibc228_x86_64.json": {
		Implementation: "pp", PyMajor: 3, PyMinor: 10, ImplMajor: 7, ImplMinor: 3,
		OS: "linux", Arch: "x86_64", Libc: "glibc", LibcMajor: 2, LibcMinor: 28,
	},
	"pp311_pypy73_macos14_arm64.json": {
		Implementation: "pp", PyMajor: 3, PyMinor: 11, ImplMajor: 7, ImplMinor: 3,
		OS: "macos", Arch: "arm64", MacMajor: 14, MacMinor: 0,
	},
	// A PyPy target with an unknown PyPy-side version: no implementation ABI
	// tier, but the pp<XY>-none-<plat> tier is still there.
	"pp310_noabi_windows_amd64.json": {
		Implementation: "pp", PyMajor: 3, PyMinor: 10,
		OS: "windows", Arch: "amd64",
	},
}

// TestGolden asserts that Target.Compile().Tags(), stringified in order,
// exactly matches the ordered tag list recorded by gen_goldens.py.
func TestGolden(t *testing.T) {
	files, _ := filepath.Glob("testdata/*.json")
	require.NotEmpty(t, files)
	for _, f := range files {
		name := filepath.Base(f)
		t.Run(name, func(t *testing.T) {
			var want []string
			b, err := os.ReadFile(f)
			require.NoError(t, err)
			require.NoError(t, json.Unmarshal(b, &want))
			tg, ok := goldenTargets[name]
			require.True(t, ok, "no Target mapping for %s", name)
			m, err := tg.Compile()
			require.NoError(t, err)
			var got []string
			for _, tag := range m.Tags() {
				got = append(got, tag.String())
			}
			require.Equal(t, want, got)
		})
	}
}
