// SPDX-License-Identifier: Apache-2.0 OR MIT
package tags

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// goldenTargets maps a testdata/*.json fixture base name to the Target that
// produced it. Fixtures are generated by tags/testdata/gen_goldens.py from
// the reference Python "packaging" library; see that script for exact
// generation parameters. Tasks 3/4 add the linux/macOS entries.
var goldenTargets = map[string]Target{
	"windows-amd64.json": {Implementation: "cp", PyMajor: 3, PyMinor: 11, OS: "windows", Arch: "amd64"},
	"generic-py3.json":   {Implementation: "py", PyMajor: 3, PyMinor: 11, OS: "windows", Arch: "amd64"},
}

// TestGolden asserts that Target.Compile().Tags(), stringified in order,
// exactly matches the ordered tag list recorded by gen_goldens.py.
func TestGolden(t *testing.T) {
	files, _ := filepath.Glob("testdata/*.json")
	require.NotEmpty(t, files)
	for _, f := range files {
		name := filepath.Base(f)
		t.Run(name, func(t *testing.T) {
			var want []string
			b, err := os.ReadFile(f)
			require.NoError(t, err)
			require.NoError(t, json.Unmarshal(b, &want))
			tg, ok := goldenTargets[name]
			require.True(t, ok, "no Target mapping for %s", name)
			m, err := tg.Compile()
			require.NoError(t, err)
			var got []string
			for _, tag := range m.Tags() {
				got = append(got, tag.String())
			}
			require.Equal(t, want, got)
		})
	}
}
